### ISSUE TITLE
请问一下，能实现官网上搜索范围的切换吗？全网or学术

### ISSUE THREAD

**Issue by simon2413** [LLM-Red-Team/metaso-free-api#1]

**Comment by Vinlic** [comment]
后续会跟进支持

**Comment by Vinlic** [comment]
@simon2413 
0.0.5版本已支持学术搜索
可以通过在消息中使用：学术深入搜索：XXXX，只要开头包含学术二字即可，如果不想使用指令可以用model名称指定：如detail-scholar，具体请参考README
