### ISSUE TITLE
不支持上下文和system消息

### ISSUE THREAD

**Issue by imasy1024** [LLM-Red-Team/metaso-free-api#17]
[https://github.com/LLM-Red-Team/metaso-free-api/blob/master/src/api/controllers/chat.ts](https://github.com/LLM-Red-Team/metaso-free-api/blob/master/src/api/controllers/chat.ts)
关键代码：`let latestMessage = messages[messages.length - 1]`

只用到了最后一条消息，不支持上下文和system消息

**Comment by Vinlic** [comment]
秘塔本身不支持system消息和多轮对话，为了确保效果会控制在一轮

**Comment by imasy1024** [comment]
> 秘塔本身不支持system消息和多轮对话，为了确保效果会控制在一轮

[https://metaso.cn/s/6sOf23T](https://metaso.cn/s/6sOf23T)
新版页面是支持“追问”的，应该是在服务器端session中存储了上下文。
如果保存sessionId和历史信息的对应关系，应该可以重复使用sessionId吧。

**Comment by Vinlic** [comment]
客户端通常传送的是全量上下文，我们不能将全量上下文在每次都创建多次追问，后期可能会通过原生对话方式（自行提供上一轮conversation_id）来支持追问
