### ISSUE TITLE
好像用不了了

### ISSUE THREAD

**Issue by Passerby1011** [LLM-Red-Team/metaso-free-api#18]
突然使用不了了，已经更新了token

**Comment by fugenb** [comment]
确实，我也突然用不了了

**Comment by 2413567** [comment]
确实

**Comment by xyifhgvnlo286** [comment]
是的,用不了了

**Comment by YueqingSheng** [comment]
求替代方案，国内还有哪家有好用的 AI 搜索 API 替代

**Comment by yaospacetim** [comment]
我的也是，一直报请求太多的错误

**Comment by Passerby1011** [comment]
> 求替代方案，国内还有哪家有好用的 AI 搜索 API 替代

同作者的 glm-search，或者微软的 bingai，搜索用着还行

**Comment by TopWinStudio1984** [comment]
我也是不能用追过来看的。确实不能用了。too many requests。

**Comment by rhinewg** [comment]
不能用了

**Comment by Vinlic** [comment]
0.0.9版本，已跟进应对官方反逆向策略，现已恢复可用。

**Comment by Vinlic** [comment]
0.0.16采用了新的技术方案捕获响应流，可以切换到该版本，应该能够顶一段时间
