### ISSUE TITLE
[error][index<980,22>] Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by huawuhen** [LLM-Red-Team/metaso-free-api#21]
对话无反应；查看日志报错如下：
> [2024-08-04 12:32:27.315][error][index<980,22>] Error [ERR_STREAM_WRITE_AFTER_END]: write after end
,[2024-08-04 12:32:27.314][success][index<1257,22>] Stream has completed transfer 7ms
,  headerSent: true

**Comment by Vinlic** [comment]
检查网络或token，目前未复现这类问题
